version: '3.7'
services:
    gateway:
        build:
            context: gateway/docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "3000:80"
    static:
        build:
            context: static/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./:/app
    webpack-watch:
        build:
            context: webpack/docker
            dockerfile: development/Dockerfile
        ports: 
            - "9228:9229"
        volumes:
            - ./:/app
        command: sh -c "until [ -f .npm-ready ] ; do sleep 1 ; done && npm run start:webpack-watch"
    node-cli:
        image: node:alpine
        working_dir: /app
        volumes: 
            - ./:/app
    myapp:
        build:
            context: server/docker
            dockerfile: development/Dockerfile
        ports: 
            - "9229:9229"
        volumes: 
            - ./:/app
        command: sh -c "until [ -f .npm-ready ] ; do sleep 1 ; done && wait-for-it mongodb:27017 -t 60 && npm run start:server"  
    mongodb:
        image: mongo
        volumes: 
            - mongodata:/data/db
        ports:
            - "27017:27017"

volumes:
    mongodata:
