version: '3.7'
services:
    gateway:
        image: ${REGISTRY}/rfr-gateway:${IMAGE_TAG}
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "443:443"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints: [node.role == manager]
    static:
        image: ${REGISTRY}/rfr-static:${IMAGE_TAG}
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints: [node.role == manager]
    myapp:
        image: ${REGISTRY}/rfr-server:${IMAGE_TAG}
        command: npm run prod-server
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints: [node.role == manager]
    mongodb:
        image: mongo
        volumes: 
            - mongodata:/data/db
        deploy:
            placement:
                constraints: [node.role == manager]
            endpoint_mode: dnsrr

volumes:
    mongodata: