version: '3.7'
services:
    gateway:
        build:
            context: gateway/docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "3000:80"
    static:
        build:
            context: static/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./dist:/app/dist
    myapp:
        build:
            context: server/docker
            dockerfile: development/Dockerfile
        volumes:
            - ./:/app
        command: sh -c "until [ -f .npm-ready ] ; do sleep 1 ; done && npm start"
    node-cli:
        image: node:alpine
        working_dir: /app
        volumes: 
            - ./:/app
