version: '3.7'
services:
    gateway:
        image: ${REGISTRY}/rfr-gateway:${IMAGE_TAG}
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "443:443"
        deploy:
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                # на менеджере потому что тут сертификаты лежат
                constraints: [node.role == manager]
    static:
        image: ${REGISTRY}/rfr-static:${IMAGE_TAG}
        deploy:
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
    myapp:
        image: ${REGISTRY}/rfr-server:${IMAGE_TAG}
        deploy:
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
    mongodb:
        image: mongo
        volumes: 
            - mongodata:/data/db
        deploy:
            placement:
                # на менеджере потому что тут mongo_data сразу разместилась,
                # когда нибудь сделаю отдельную виртуалку [node.labels.db == db]
                constraints: [node.role == manager]
            endpoint_mode: dnsrr

volumes:
    mongodata: