export const CALL_API = Symbol('Call API');

export const CALL_API_ACTION = 'CALL_API_ACTION';
export const SET_USER_REGISTER_FORM_ERRORS = 'SET_USER_REGISTER_FORM_ERRORS';

export const LOAD_MY_DATA_REQUEST = 'LOAD_MY_DATA_REQUEST';
export const LOAD_MY_DATA_SUCCESS = 'LOAD_MY_DATA_SUCCESS';
export const LOAD_MY_DATA_FAILURE = 'LOAD_MY_DATA_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const COMPONENT_LOADING_SUCCESS = 'COMPONENT_LOADING_SUCCESS';
