export const CALL_API = Symbol('Call API')

export const LOAD_MY_DATA_REQUEST = 'LOAD_MY_DATA_REQUEST'
export const LOAD_MY_DATA_SUCCESS = 'LOAD_MY_DATA_SUCCESS'
export const LOAD_MY_DATA_FAILURE = 'LOAD_MY_DATA_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const COMPONENT_LOADING_SUCCESS = 'COMPONENT_LOADING_SUCCESS';
