export const CALL_API = Symbol('Call API');

export const CALL_API_ACTION = 'CALL_API_ACTION';
export const SET_USER_REGISTER_FORM_ERRORS = 'SET_USER_REGISTER_FORM_ERRORS';
export const SET_LOGIN_FORM_ERRORS = 'SET_LOGIN_FORM_ERRORS';

export const NEW_EVENT_REQUEST = 'NEW_EVENT_REQUEST';
export const NEW_EVENT_SUCCESS = 'NEW_EVENT_SUCCESS';
export const NEW_EVENT_FAILURE = 'NEW_EVENT_FAILURE';

export const LOAD_MY_DATA_REQUEST = 'LOAD_MY_DATA_REQUEST';
export const LOAD_MY_DATA_SUCCESS = 'LOAD_MY_DATA_SUCCESS';
export const LOAD_MY_DATA_FAILURE = 'LOAD_MY_DATA_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const COMPONENT_LOADING_SUCCESS = 'COMPONENT_LOADING_SUCCESS';
